language: node_js
node_js:
  - "11.0"
sudo: required
branches:
  only:
    - master
cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli
  - npm install gulp
script:
  - npm install
  - ng lint
  - ng build --prod --base-href /about-me/
  - gulp purifyCSS
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/about-me
  on:
    branch: master
